//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touhou_Project_Mod_UI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Touhou_Project_Mod_UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Touhou Chireiden 的本地化字符串。
        /// </summary>
        public static string Chireiden {
            get {
                return ResourceManager.GetString("Chireiden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touhou Eiyashou 的本地化字符串。
        /// </summary>
        public static string Eiyashou {
            get {
                return ResourceManager.GetString("Eiyashou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touhou Fuujinroku 的本地化字符串。
        /// </summary>
        public static string Fuujinroku {
            get {
                return ResourceManager.GetString("Fuujinroku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invincible 的本地化字符串。
        /// </summary>
        public static string Invincible {
            get {
                return ResourceManager.GetString("Invincible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touhou Juuouen 的本地化字符串。
        /// </summary>
        public static string Juuouen {
            get {
                return ResourceManager.GetString("Juuouen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touhou Kaeizuka 的本地化字符串。
        /// </summary>
        public static string Kaeizuka {
            get {
                return ResourceManager.GetString("Kaeizuka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touhou Kanjuden 的本地化字符串。
        /// </summary>
        public static string Kanjuden {
            get {
                return ResourceManager.GetString("Kanjuden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touhou Kikeijuu 的本地化字符串。
        /// </summary>
        public static string Kikeijuu {
            get {
                return ResourceManager.GetString("Kikeijuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touhou Kishinjou 的本地化字符串。
        /// </summary>
        public static string Kishinjou {
            get {
                return ResourceManager.GetString("Kishinjou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touhou Koumakyou 的本地化字符串。
        /// </summary>
        public static string Koumakyou {
            get {
                return ResourceManager.GetString("Koumakyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touhou Kouryuudou 的本地化字符串。
        /// </summary>
        public static string Kouryuudou {
            get {
                return ResourceManager.GetString("Kouryuudou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lock Bomb 的本地化字符串。
        /// </summary>
        public static string LockBomb {
            get {
                return ResourceManager.GetString("LockBomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lock Player 的本地化字符串。
        /// </summary>
        public static string LockPlayer {
            get {
                return ResourceManager.GetString("LockPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Power 的本地化字符串。
        /// </summary>
        public static string MaxPower {
            get {
                return ResourceManager.GetString("MaxPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No results found 的本地化字符串。
        /// </summary>
        public static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touhou Seirensen 的本地化字符串。
        /// </summary>
        public static string Seirensen {
            get {
                return ResourceManager.GetString("Seirensen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touhou Shinreibyou 的本地化字符串。
        /// </summary>
        public static string Shinreibyou {
            get {
                return ResourceManager.GetString("Shinreibyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touhou Tenkuushou 的本地化字符串。
        /// </summary>
        public static string Tenkuushou {
            get {
                return ResourceManager.GetString("Tenkuushou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touhou Youyoumu 的本地化字符串。
        /// </summary>
        public static string Youyoumu {
            get {
                return ResourceManager.GetString("Youyoumu", resourceCulture);
            }
        }
    }
}
